import os
import requests
import json
import random
# Set Vestaboard API key
VBKEY = "0c86c47a+ebb0+4158+b59d+a9c3d5838482"
# Set Vestaboard URL
url = "https://rw.vestaboard.com/"
# Create header
headers = {
'X-Vestaboard-Read-Write-Key': VBKEY,
'Content-Type': 'application/json'
}

def random_sentence():
 sentences = [
 "Be as you wish to seem",
"Talk doesn't cook rice",
"Joy is the best makeup",
"Well begun is half done",
"You give before you get",
"Wisdom begins in wonder",
"The cautious seldom err",
"Do more than dream: work",
"What we think, we become",
"A jug fills drop by drop",
"Light tomorrow with today",
"Fortune favours the brave",
"Take it easy, but take it",
"Peace begins with a smile",
"Everything in life is luck",
"Skill to do comes of doing",
"Fortune befriends the bold",
"He who is contented is rich",
"Imagination rules the world",
"Never, never, never give up",
"Our passion is our strength",
"What worries you masters you",
"Who sows virtue reaps honour",
"The shortest answer is doing",
"Speak low, if you speak love",
"A stumble may prevent a fall",
"Smile, breathe and go slowly",
"A good rest is half the work",
"What you give is what you get",
"Change in all things is sweet",
"Smile, breathe, and go slowly",
"The beginning is always today",
"When in doubt, tell the truth",
"Open minds lead to open doors",
"Do, or do not. There is no try",
"Our distrust is very expensive",
"No man was ever wise by chance",
"No garden is without its weeds",
"He who angers you conquers you",
"Be the chief but never the lord",
"To lead people walk behind them",
"A rolling stone gathers no moss",
"The world is always in movement",
"You have to believe in yourself",
"Each day provides its own gifts",
"Kindness is the greatest wisdom",
"You only lose what you cling to",
"Things do not change, we change",
"Things do not change; we change",
"Never mistake motion for action",
"Nothing will work unless you do",
"One today is worth two tomorrows",
"One fails forward toward success",
"He is able who thinks he is able",
"Silence is a fence around wisdom",
"Happiness depends upon ourselves",
"All is flux; nothing stays still",
"You'll see it when you believe it",
"God always takes the simplest way",
"Only do what your heart tells you",
"A goal is a dream with a deadline",
"Truth is powerful and it prevails",
"Our intention creates our reality",
"I think and that is all that I am",
"If you wish to be a writer, write",
"Ignorance never settle a question",
"As you think, so shall you become",
"Being angry never solves anything",
"Well done is better than well said",
"A beautiful thing is never perfect",
"If you can dream it, you can do it",
"Rainbows apologize for angry skies",
"Everything you can imagine is real",
"The best way out is always through",
"To fly, we have to have resistance",
"Memory is the mother of all wisdom",
"Be slow of tongue and quick of eye",
"To be great is to be misunderstood",
"We can only learn to love by loving",
"Having nothing, nothing can he lose",
"One faces the future with ones past",
"When deeds speak, words are nothing",
"We do what we do because we believe",
"Kind words will unlock an iron door",
"Patience is the companion of wisdom",
"All things change; nothing perishes",
"Absence makes the heart grow fonder",
"You won't skid if you stay in a rut",
"He who knows himself is enlightened",
"All great achievements require time",
"Try and fail, but don't fail to try",
"A goal without a plan is just a wish",
"Time is the wisest counsellor of all",
"You can do it if you believe you can!",
"Everyone smiles in the same language",
"Life is just a chance to grow a soul",
"Keep true to the dreams of thy youth",
"Knowing is not enough; we must apply!",
"I allow my intuition to lead my path",
"Whoso loves, believes the impossible",
"Change your words. Change your world",
"When you lose, don't lose the lesson",
"You cannot have what you do not want",
"Almost everything comes from nothing",
"It's simple, if it jiggles, it's fat",
"Fate is in your hands and no one else's",
"Nothing happens unless first we dream",
"Self-complacency is fatal to progress",
"All serious daring starts from within",
"Whatever happens, take responsibility",
"He who talks more is sooner exhausted",
"Life is a progress, and not a station",
"No one has ever become poor by giving",
"A man is great by deeds, not by birth",
"Silence is a source of great strength",
"We aim above the mark to hit the mark",
"Great acts are made up of small deeds",
"They can conquer who believe they can",
"You can observe a lot just by watching",
"Never mistake activity for achievement",
"Without courage, wisdom bears no fruit",
"All know the way; few actually walk it",
"Do one thing every day that scares you",
"From little acorns mighty oaks do grow",
"The greatest remedy for anger is delay",
"Change your thoughts, change your life!",
"Worry gives a small thing a big shadow",
"Time you enjoy wasting, was not wasted",
"What we see is mainly what we look for",
"My reputation grows with every failure",
"Begin, be bold, and venture to be wise",
"Example has more followers than reason",
"From small beginnings come great things",
"Wisdom is the supreme part of happiness",
"Victory belongs to the most persevering",
"Love all, trust a few, do wrong to none",
"In order to win, you must expect to win",
"Some pursue happiness, others create it",
"Reality leaves a lot to the imagination",
"Wherever you go, go with all your heart",
"Freedom is the right to live as we wish",
"A short saying oft contains much wisdom",
"Sadness flies away on the wings of time",
"The pain passes, but the beauty remains",
"Put your future in good hands, your own",
"From wonder into wonder existence opens",
"Much wisdom often goes with fewer words",
"Time you enjoyed wasting was not wasted",
"Never promise more than you can perform",
"Once you choose hope, anythings possible",
"The simplest things are often the truest",
"Someone is special only if you tell them",
"Our strength grows out of our weaknesses",
"We must become the change we want to see",
"Put your future in good hands : your own",
"A prudent question is one half of wisdom",
"No is easier to do. Yes is easier to say",
"The price of greatness is responsibility",
"You always succeed in producing a result",
"Most smiles are started by another smile",
"I walk slowly, but I never walk backward",
"Love is the flower you've got to let grow",
"Great talent finds happiness in execution",
"A short saying often contains much wisdom",
"The only real valuable thing is intuition",
"Self-trust is the first secret of success",
"The wisest men follow their own direction",
"When you learn, teach. When you get, give",
"To see things in the seed, that is genius",
"We lost because we told ourselves we lost",
"Gratitude is riches. Complaint is poverty",
"Every man dies. Not every man really lives",
"The harder you fall, the higher you bounce",
"It is better to travel well than to arrive",
"Silence is a true friend who never betrays",
"Fear is a darkroom where negatives develop",
"You're never a loser until you quit trying",
"Either you run the day or the day runs you",
"You can't shake hands with a clenched fist",
"If a man does his best, what else is there?",
"If you come to a fork in the road, take it",
"You can't choose up sides on a round world",
"The universe is made of stories, not atoms",
"The best cure for the body is a quiet mind",
"The more you care, the stronger you can be",
"You teach best what you most need to learn",
"The only way to have a friend is to be one",
"A house divided against itself cannot stand",
"Trouble is only opportunity in work clothes",
"A weed is no more than a flower in disguise",
"Don't ruin the present with the ruined past",
"Fears are nothing more than a state of mind",
"Imagination is the highest kite one can fly",
"No man is free who is not master of himself",
"They can do all because they think they can",
"Be yourself; everyone else is already taken",
"Growth itself contains the germ of happiness",
"Once we accept our limits, we go beyond them",
"Be great in act, as you have been in thought",
"Yesterdays home runs don't win today's games",
"An ant on the move does more than a dozing ox",
"Error is discipline through which we advance",
"Worry often gives a small thing a big shadow",
"Excellence is not a skill. It is an attitude",
"Whoever is happy will make others happy, too",
"The world is but a canvas to the imagination",
"If I know what love is, it is because of you",
"A man's dreams are an index to his greatness",
"Either I will find a way, or I will make one",
"Bite off more than you can chew, then chew it",
"To succeed, we must first believe that we can",
"Don't wait. The time will never be just right",
"Anticipate the difficult by managing the easy",
"He that is giddy thinks the world turns round",
"Do something wonderful, people may imitate it",
"The truest wisdom is a resolute determination",
"If you surrender to the wind, you can ride it",
"If there is no struggle, there is no progress",
"Every problem has a gift for you in its hands",
"The secret of success is constancy to purpose",
"All I can say about life is, Oh God, enjoy it!",
"When the solution is simple, God is answering",
"Silence is the true friend that never betrays",
"The day you decide to do it is your lucky day",
"Nothing diminishes anxiety faster than action",
"Learning is finding out what you already know",
"Do good by stealth, and blush to find it fame",
"Action is the foundational key to all success",
"I never worry about action, but only inaction",
"If you want a thing done well, do it yourself",
"Be like the flower, turn your face to the sun",
"The energy of the mind is the essence of life",
"Ideas are the beginning points of all fortunes",
"Study the past, if you would divine the future",
"The years teach much which the days never know",
"Faith in oneself is the best and safest course",
"Life is the flower for which love is the honey",
"There is no failure except in no longer trying",
"Nature takes away any faculty that is not used",
"There never was a good knife made of bad steel",
"Blaze with the fire that is never extinguished",
"Do not turn back when you are just at the goal",
"We must not say every mistake is a foolish one",
"Always be smarter than the people who hire you",
"A man is not where he lives but where he loves",
"Where all think alike, no one thinks very much",
"He who fears being conquered is sure of defeat",
"As our case is new, we must think and act anew",
"You have to think anyway, so why not think big?",
"A thing well said will be wit in all languages",
"If you aren't going all the way, why go at all?",
"Let the beauty of what you love be what you do",
"Fear not for the future, weep not for the past",
"We make our own fortunes and we call them fate",
"You must do the things you think you cannot do",
"Miracles come in moments. Be ready and willing",
"Music in the soul can be heard by the universe",
"What we see depends mainly on what we look for",
"An ounce of emotion is equal to a ton of facts",
"Peace comes from within. Do not seek it without",
"I believe that every person is born with talent",
"Character develops itself in the stream of life",
"Time is the most valuable thing a man can spend",
"Begin to weave and God will give you the thread",
"To enjoy life, we must touch much of it lightly",
"What you see depends on what you're looking for",
"Myths which are believed in tend to become true",
"Take heed: you do not find what you do not seek",
"Everything has beauty, but not everyone sees it",
"Chaos and Order are not enemies, only opposites",
"There is nothing impossible to him who will try",
"Be the change that you want to see in the world",
"Remember that failure is an event, not a person",
"Go for it now. The future is promised to no one",
"I have never been hurt by anything I didn't say",
"I will prepare and some day my chance will come",
"Start wide, expand further, and never look back",
"Life is a learning experience, only if you learn",
"Today is the tomorrow we worried about yesterday",
"The day is already blessed, find peace within it",
"Goals are the fuel in the furnace of achievement",
"Be kind whenever possible. It is always possible",
"Nothing strengthens authority so much as silence",
"If the shoe doesn't fit, must we change the foot?",
"We choose our destiny in the way we treat others",
"I destroy my enemies when I make them my friends",
"Better be ignorant of a matter than half know it",
"To want to be what one can be is purpose in life",
"The foot feels the foot when it feels the ground",
"We know what we are, but know not what we may be",
"Give thanks for a little and you will find a lot",
"Listen to what you know instead of what you fear",
"Life is change. Growth is optional. Choose wisely",
"I never think of the future. It comes soon enough",
"Important principles may, and must, be inflexible",
"It takes both sunshine and rain to make a rainbow",
"Good luck is another name for tenacity of purpose",
"Today is the tomorrow you worried about yesterday",
"The day always looks brighter from behind a smile",
"Inspiration exists, but it has to find us working",
"Don't compromise yourself. You are all you've got",
"The cause is hidden. The effect is visible to all",
"The mind is everything. What you think you become",
"There is no greater harm than that of time wasted",
"Never put off till tomorrow what you can do today",
"Correction does much, but encouragement does more",
"Time stays long enough for anyone who will use it",
"The awareness of our own strength makes us modest",
"You are special, you are unique, you are the best!",
"Act as if what you do makes a difference. It does",
"Never let lack of money interfere with having fun",
"The ladder of success is never crowded at the top",
"Those that know, do. Those that understand, teach",
"Every man is a volume if you know how to read him",
"The time you think you're missing, misses you too",
"Failure is not an option. Everyone has to succeed",
"From error to error one discovers the entire truth",
"Yesterday I dared to struggle. Today I dare to win",
"Experience is simply the name we give our mistakes",
"There is no way to happiness, happiness is the way",
"What we achieve inwardly will change outer reality",
"Happiness is found in doing, not merely possessing",
"Write your plans in pencil and give God the eraser",
"I have often regretted my speech, never my silence",
"The way is not in the sky. The way is in the heart",
"He who is fixed to a star does not change his mind",
"Don't look back. Something might be gaining on you",
"Who we are never changes. Who we think we are does",
"In the middle of every difficulty lies opportunity",
"Nothing great was ever achieved without enthusiasm",
"Be your own hero, it's cheaper than a movie ticket",
"Ability will never catch up with the demand for it",
"To climb steep hills requires a slow pace at first",
"You really can change the world if you care enough",
"To hell with circumstances; I create opportunities",
"Difficulties increase the nearer we get to the goal",
"Trust yourself. You know more than you think you do",
"The undertaking of a new action brings new strength",
"Every new day is another chance to change your life",
"If you cannot be silent be brilliant and thoughtful",
"Who looks outside, dreams; who looks inside, awakes",
"Trusting our intuition often saves us from disaster",
"You can't stop the waves, but you can learn to surf",
"No snowflake in an avalanche ever feels responsible",
"Problems are only opportunities with thorns on them",
"The heart has its reasons which reason knows not of",
"Your big opportunity may be right where you are now",
"History will be kind to me for I intend to write it",
"Formula for success: under promise and over deliver",
"He who obtains has little. He who scatters has much",
"It is never too late to be what you might have been",
"The world doesn't happen to you it happens from you",
"The heart has eyes which the brain knows nothing of",
"Don't wait for people to be friendly. Show them how",
"Freedom is what you do with what's been done to you",
"We are all something, but none of us are everything",
"Quality means doing it right when no one is looking",
"A man is not old as long as he is seeking something",
"Do what you can. Want what you have. Be who you are",
"Why worry about tomorrow, when today is all we have?",
"Sometimes the biggest act of courage is a small one",
"Things that were hard to bear are sweet to remember",
"Just trust yourself, then you will know how to live",
"We read the world wrong and say that it deceives us",
"In skating over thin ice our safety is in our speed",
"The best way to predict your future is to create it",
"Work out your own salvation. Do not depend on others",
"The best teacher is experience learned from failures",
"The two most powerful warriors are patience and time",
"All our knowledge has its origins in our perceptions",
"I believe in one thing only, the power of human will",
"There is no way to prosperity, prosperity is the way",
"The journey of a thousand miles begins with one step",
"Where there is great love, there are always miracles",
"A man sees in the world what he carries in his heart",
"Most powerful is he who has himself in his own power",
"What is not started today is never finished tomorrow",
"When I let go of what I am, I become what I might be",
"A day of worry is more exhausting than a day of work",
"The best thing in every noble dream is the dreamer..",
"Doing nothing is better than being busy doing nothing",
"Life is movement-we breathe, we eat, we walk, we move!",
"While we stop to think, we often miss our opportunity",
"Autumn is a second spring when every leaf is a flower",
"Kind words do not cost much. Yet they accomplish much",
"I've never seen a smiling face that was not beautiful",
"Our lives are a sum total of the choices we have made",
"Your future depends on many things, but mostly on you",
"When fate hands us a lemon, lets try to make lemonade",
"In seed time learn, in harvest teach, in winter enjoy",
"Every gift from a friend is a wish for your happiness",
"Only when we are no longer afraid do we begin to live",
"Life is what happens while you are making other plans",
"When anger use your energy to do something productive",
"Excellence is to do a common thing in an uncommon way",
"Just as much as we see in others we have in ourselves",
"We cannot direct the wind but we can adjust the sails",
"Think like a man of action; act like a man of thought",
"A wise man will make more opportunities than he finds",
"No one can make you feel inferior without your consent",
"Set your goals high, and don't stop till you get there",
"Life shrinks or expands in proportion to one's courage",
"Reality does not conform to the ideal, but confirms it",
"A really great talent finds its happiness in execution",
"Mountains cannot be surmounted except by winding paths",
"Pick battles big enough to matter, small enough to win",
"Don't cry because it's over. Smile because it happened",
"Silence is deep as Eternity, Speech is shallow as Time",
"Don't smother each other. No one can grow in the shade",
"The best way to pay for a lovely moment is to enjoy it",
"Wherever a man turns he can find someone who needs him",
"Action will remove the doubts that theory cannot solve",
"As long as your going to be thinking anyway, think big",
"Arriving at one point is the starting point to another",
"No day in which you learn something is a complete loss",
"Decision is a risk rooted in the courage of being free",
"There is no great genius without some touch of madness",
"If you can't feed a hundred people, then feed just one",
"The greatest barrier to success is the fear of failure",
"Always seek out the seed of triumph in every adversity",
"Wrinkles should merely indicate where smiles have been",
"Do not wait for leaders; do it alone, person to person",
"If it's hard to remember, it'll be difficult to forget",
"It's easier to see the mistakes on someone else's paper",
"Learn from yesterday, live for today, hope for tomorrow",
"What you fear is that which requires action to overcome",
"Luck is what happens when preparation meets opportunity",
"Don't be pushed by your problems; be led by your dreams",
"When you doubt your power, you give power to your doubt",
"Minds are like parachutes. They only function when open",
"To avoid criticism, do nothing, say nothing, be nothing",
"It is fatal to enter any war without the will to win it",
"Can you imagine what I would do if I could do all I can?",
"No act of kindness, no matter how small, is ever wasted",
"No matter how hard the past, you can always begin again",
"I begin with an idea and then it becomes something else",
"There are people who have money and people who are rich",
"Keep your eyes on the stars and your feet on the ground",
"If you kick a stone in anger, you'll hurt your own foot",
"Anybody can make history. Only a great man can write it",
"Truth is generally the best vindication against slander",
"Think how hard physics would be if particles could think",
"Argue for your limitations, and sure enough theyre yours",
"No alibi will save you from accepting the responsibility",
"A good plan today is better than a perfect plan tomorrow",
"Science is organized knowledge. Wisdom is organized life",
"Difficulties are things that show a person what they are",
"To accomplish great things, we must dream as well as act",
"Intuition will tell the thinking mind where to look next",
"A good decision is based on knowledge and not on numbers",
"People seldom notice old clothes if you wear a big smile",
"We must embrace pain and burn it as fuel for our journey",
"Nobody can do everything, but everybody can do something",
"For everything that lives is holy, life delights in life",
"See the positive side, the potential, and make an effort",
"Love is the master key that opens the gates of happiness",
"For success, attitude is equally as important as ability",
"I have no special talent. I am only passionately curious",
"Nobody will believe in you unless you believe in yourself",
"The more you know yourself, the more you forgive yourself",
"The path to success is to take massive, determined action",
"To be wrong is nothing unless you continue to remember it",
"Those who will play with cats must expect to be scratched",
"God has given you one face, and you make yourself another",
"You must welcome change as the rule but not as your ruler",
"The eye sees only what the mind is prepared to comprehend",
"Be less curious about people and more curious about ideas",
"Take rest; a field that has rested gives a bountiful crop",
"You are the only person on Earth who can use your ability",
"Beauty is not in the face; beauty is a light in the heart",
"We may encounter many defeats but we must not be defeated",
"Make the most of yourself for that is all there is of you",
"It takes courage to grow up and become who you really are",
"Knowledge rests not upon truth alone, but upon error also",
"You are the only person on earth who can use your ability",
"The less effort, the faster and more powerful you will be",
"Remembering a wrong is like carrying a burden on the mind",
"Moments of complete apathy are the best for new creations",
"There is only one happiness in life, to love and be loved",
"Most folks are as happy as they make up their minds to be",
"We never live; we are always in the expectation of living",
"Argue for your limitations, and sure enough they're yours",
"Those who are free of resentful thoughts surely find peace",
"Friendship isn't a big thing. It's a million little things",
"The mind unlearns with difficulty what it has long learned",
"Strong beliefs win strong men, and then make them stronger",
"What you do not want done to yourself, do not do to others",
"More powerful than the will to win is the courage to begin",
"I know but one freedom and that is the freedom of the mind",
"Complaining doesn't change a thing only taking action does",
"Make the most of yourself, for that is all there is of you",
"He who knows, does not speak. He who speaks, does not know",
"A person who never made a mistake never tried anything new",
"He who knows that enough is enough will always have enough",
"Learning is a treasure that will follow its owner everywhere",
"Keep yourself to the sunshine and you cannot see the shadow",
"How we spend our days is, of course, how we spend our lives",
"The world makes way for the man who knows where he is going",
"Meaning is not what you start with but what you end up with",
"To be wronged is nothing unless you continue to remember it",
"Life is 10% what happens to you and 90% how you react to it",
"Sooner or later, those who win are those who think they can",
"Reality is merely an illusion, albeit a very persistent one",
"If you smile when no one else is around, you really mean it",
"You need chaos in your soul to give birth to a dancing star",
"We shall never know all the good that a simple smile can do",
"Spring is a time for rebirth and the fulfilment of new life",
"The most successful people are those who are good at plan B",
"We know the truth, not only by the reason, but by the heart",
"Those who cannot learn from history are doomed to repeat it",
"Be a good listener. Your ears will never get you in trouble",
"If you have knowledge, let others light their candles in it",
"Adversity causes some men to break, others to break records",
"Nothing is a waste of time if you use the experience wisely",
"It is not in the stars to hold our destiny but in ourselves",
"Nothing in life is to be feared. It is only to be understood",
"I cannot make my days longer so I strive to make them better",
"In all things of nature there is something of the marvellous",
"Watch the little things; a small leak will sink a great ship",
"Not what we have but what we enjoy constitutes our abundance",
"Only those who dare to fail greatly can ever achieve greatly",
"Stay away from what might have been and look at what will be",
"Each day can be one of triumph if you keep up your interests",
"Nature is a mutable cloud which is always and never the same",
"Life is what you make of it. Always has been, always will be",
"As we risk ourselves, we grow. Each new experience is a risk",
"Every human being is the author of his own health or disease",
"Nothing is at last sacred but the integrity of your own mind",
"Be here now. Be someplace else later. Is that so complicated?",
"We can do no great things, only small things with great love",
"Gratitude is the fairest blossom which springs from the soul",
"The only real mistake is the one from which we learn nothing",
"When people are like each other they tend to like each other",
"I can't believe that God put us on this earth to be ordinary",
"The future is green energy, sustainability, renewable energy",
"Loss is nothing else but change,and change is Natures delight",
"The doors we open and close each day decide the lives we live",
"I'm not afraid of storms, for Im learning how to sail my ship",
"If you cannot do great things, do small things in a great way",
"It is in your moments of decision that your destiny is shaped",
"Know, first, who you are, and then adorn yourself accordingly",
"When you come to the end of your rope, tie a knot and hang on",
"Go put your creed into the deed. Nor speak with double tongue",
"It can't be spring if your heart is filled with past failures",
"He who has imagination without learning has wings but no feet",
"Be sure you put your feet in the right place, then stand firm",
"We choose our joys and sorrows long before we experience them",
"You cannot be lonely if you like the person you're alone with",
"Life is really simple, but we insist on making it complicated",
"Society develops wit, but its contemplation alone forms genius",
"You can do what's reasonable or you can decide what's possible",
"Never ignore a gut feeling, but never believe that it's enough",
"Life is a process. We are a process. The universe is a process",
"Better to have loved and lost, than to have never loved at all",
"Don't be afraid to go out on a limb. That's where the fruit is",
"Always be mindful of the kindness and not the faults of others",
"All the flowers of all the tomorrows are in the seeds of today",
"In all chaos there is a cosmos, in all disorder a secret order",
"The greatest obstacle to connecting with our joy is resentment",
"He who has health has hope, and he who has hope has everything",
"Respect should be earned by actions, and not acquired by years",
"All action results from thought, so it is thoughts that matter",
"Your attitude, not your aptitude, will determine your altitude",
"Sometimes by losing a battle you find a new way to win the war",
"Don't settle for a relationship that won't let you be yourself",
"Yeah we all shine on, like the moon, and the stars, and the sun",
"Most people are about as happy as they make up their minds to be",
"No man can succeed in a line of endeavor which he does not like",
"It does not matter how slowly you go as long as you do not stop",
"Most folks are about as happy as they make up their minds to be",
"An obstacle may be either a stepping stone or a stumbling block",
"It is better to understand a little than to misunderstand a lot",
"You don't drown by falling in water. You drown by staying there",
"We must not allow ourselves to become like the system we oppose",
"Real success is finding your lifework in the work that you love",
"All men who have achieved great things have been great dreamers",
"Don't talk about what you have done or what you are going to do",
"Kindness is the golden chain by which society is bound together",
"Life is a succession of moments. To live each one is to succeed",
"Impossibilities are merely things which we have not yet learned",
"Always do your best. What you plant now, you will harvest later",
"Don't let what you can't do stop you from doing what you can do",
"If only wed stop trying to be happy wed have a pretty good time",
"Great is the art of beginning, but greater is the art of ending",
"When performance exceeds ambition, the overlap is called success",
"We learn what we have said from those who listen to our speaking",
"We cannot do everything at once, but we can do something at once",
"If it is not right do not do it; if it is not true do not say it",
"Without some goals and some efforts to reach it, no man can live",
"The only limit to your impact is your imagination and commitment",
"Small opportunities are often the beginning of great enterprises",
"Your sacred space is where you can find yourself again and again",
"People may doubt what you say, but they will believe what you do",
"The one who always loses, is the only person who gets the reward",
"Experience keeps a dear school, but fools will learn in no other",
"You cannot travel the path until you have become the path itself",
"I hear and I forget. I see and I remember. I do and I understand",
"Great ideas often receive violent opposition from mediocre minds",
"To follow, without halt, one aim: There is the secret of success",
"There are no limitations to the mind except those we acknowledge",
"He who knows others is wise. He who knows himself is enlightened",
"Life is what happens to you while you're busy making other plans",
"To bring anything into your life, imagine that it's already there",
"May our hearts garden of awakening bloom with hundreds of flowers",
"Follow your instincts. That is where true wisdom manifests itself",
"Think as a wise man but communicate in the language of the people",
"To be upset over what you don't have is to waste what you do have",
"Short words are best and the old words when short are best of all",
"If you light a lamp for somebody, it will also brighten your path",
"The secret to a rich life is to have more beginnings than endings",
"The world is a book, and those who do not travel read only a page",
"Tension is who you think you should be. Relaxation is who you are",
"Shoot for the moon. Even if you miss, you'll land among the stars",
"You can't trust without risk but neither can you live in a cocoon",
"To know oneself is to study oneself in action with another person",
"Freedom is not worth having if it does not connote freedom to err",
"It isn't where you come from, it's where you're going that counts",
"The most formidable weapon against errors of every kind is reason",
"I may not know everything, but everything is not known yet anyway",
"Fame usually comes to those who are thinking about something else",
"The cure for boredom is curiosity. There is no cure for curiosity",
"The deepest craving of human nature is the need to be appreciated",
"Better than a thousand hollow words is one word that brings peace",
"Courage is going from failure to failure without losing enthusiasm",
"Life isn't about finding yourself. Life is about creating yourself",
"Without faith, nothing is possible. With it, nothing is impossible",
"I never see what has been done; I only see what remains to be done",
"If we did the things we are capable of, we would astound ourselves",
"Love is just a word until someone comes along and gives it meaning",
"Every day may not be good, but there's something good in every day",
"There are no failures. Just experiences and your reactions to them",
"Better than a thousand hollow words, is one word that brings peace",
"Nothing ever goes away until it has taught us what we need to know",
"Experience can only be gained by doing not by thinking or dreaming",
"There are no failures, just experiences and your reactions to them",
"The truth which has made us free will in the end make us glad also",
"It is impossible to feel grateful and depressed in the same moment",
"It's not what happens to you, but how you react to it that matters",
"When there is no enemy within, the enemies outside cannot hurt you",
"We are Divine enough to ask and we are important enough to receive",
"Waste no more time arguing about what a good man should be. Be one",
"Turn your face toward the sun and the shadows will fall behind you",
"Be gentle first with yourself if you wish to be gentle with others",
"A man who doesn't trust himself can never really trust anyone else",
"When deeds and words are in accord, the whole world is transformed",
"Don't think of it as failure. Think of it as time-released success",
"Weve got to have a dream if we are going to make a dream come true",
"What is a weed? A plant whose virtues have not yet been discovered",
"The possibilities are numerous once we decide to act and not react",
"Success is determined by those whom prove the impossible, possible",
"Real magic in relationships means an absence of judgement of others",
"The winds and waves are always on the side of the ablest navigators",
"The bird of paradise alights only upon the hand that does not grasp",
"If one does not know to which port is sailing, no wind is favorable",
"If you get up one more time than you fall, you will make it through",
"Never idealize others. They will never live up to your expectations",
"Accept challenges, so that you may feel the exhilaration of victory",
"A man should look for what is, and not for what he thinks should be",
"He who conquers others is strong; He who conquers himself is mighty",
"Anything you really want, you can attain, if you really go after it",
"Success is getting what you want. Happiness is wanting what you get",
"To be tested is good. The challenged life may be the best therapist",
"Love is the only force capable of transforming an enemy into friend",
"Saying thank you is more than good manners. It is good spirituality",
"Go to your bosom: Knock there, and ask your heart what it doth know",
"If you can't explain it simply, you don't understand it well enough",
"The difficulties of life are intended to make us better, not bitter",
"To be happy is to be able to become aware of oneself without fright",
"We make a living by what we get, but we make a life by what we give",
"The best place to find a helping hand is at the end of your own arm",
"Reason and free inquiry are the only effectual agents against error",
"I gave my life to become the person I am right now. Was it worth it?",
"It is impossible for a man to learn what he thinks he already knows",
"Numberless are the worlds wonders, but none more wonderful than man",
"When you judge another, you do not define them, you define yourself",
"The worst thing I can be is the same as everybody else. I hate that",
"Begin at once to live and count each separate day as a separate life",
"Think for yourselves and let others enjoy the privilege to do so too",
"I always wanted to be somebody, but I should have been more specific",
"If you correct your mind, the rest of your life will fall into place",
"Three things cannot be long hidden: the sun, the moon, and the truth",
"The free man is he who does not fear to go to the end of his thought",
"All achievements, all earned riches, have their beginning in an idea",
"The superior man is modest in his speech, but exceeds in his actions",
"They must often change, who would be constant in happiness or wisdom",
"It is only possible to live happily ever after on a day to day basis",
"Hope arouses, as nothing else can arouse, a passion for the possible",
"Everything that exists is in a manner the seed of that which will be",
"Mistakes are always forgivable, if one has the courage to admit them",
"If you do not change direction, you may end up where you are heading",
"No yesterdays are ever wasted for those who give themselves to today",
"He who lives in harmony with himself lives in harmony with the world",
"Build a better mousetrap and the world will beat a path to your door",
"Don't let today's disappointments cast a shadow on tomorrow's dreams",
"Chaos is inherent in all compounded things. Strive on with diligence",
"Stay committed to your decisions, but stay flexible in your approach",
"Logic will get you from A to B. Imagination will take you everywhere",
"Rather than wishing for change, you first must be prepared to change",
"Thought is the blossom; language the bud; action the fruit behind it",
"Forgiveness does not change the past, but it does enlarge the future",
"To get the full value of joy you must have someone to divide it with",
"Beware of the half truth. You may have gotten hold of the wrong half",
"All seasons are beautiful for the person who carries happiness within",
"The future belongs to those who believe in the beauty of their dreams",
"Everything is perfect in the universe, even your desire to improve it",
"It has never been my object to record my dreams, just to realize them",
"Life is a succession of lessons, which must be lived to be understood",
"Happiness is not something ready made. It comes from your own actions",
"The truth is always exciting. Speak it, then. Life is dull without it",
"The universe is transformation; our life is what our thoughts make it",
"The odds of hitting your target go up dramatically when you aim at it",
"The future is completely open, and we are writing it moment to moment",
"The world turns aside to let any man pass who knows where he is going",
"It is the quality of our work which will please God, not the quantity",
"We can change our lives. We can do, have, and be exactly what we wish",
"It is not fair to ask of others what you are unwilling to do yourself",
"The only real failure in life is not to be true to the best one knows",
"One may say the eternal mystery of the world is its comprehensibility",
"Good thoughts are no better than good dreams, unless they be executed",
"If you find yourself in a hole, the first thing to do is stop digging",
"What you are is what you have been. What you'll be is what you do now",
"Genius is one percent inspiration and ninety-nine percent perspiration",
"To get something you never had, you have to do something you never did",
"To forgive is to set a prisoner free and realize that prisoner was you",
"Give thanks for the rain of life that propels us to reach new horizons",
"We all have problems. The way we solve them is what makes us different",
"So long as a person is capable of self-renewal they are a living being",
"To study and not think is a waste. To think and not study is dangerous",
"It is not enough to have a good mind; the main thing is to use it well",
"The weak can never forgive. Forgiveness is the attribute of the strong",
"Happiness is the reward we get for living to the highest right we know",
"Lose an hour in the morning, and you will spend all day looking for it",
"Imagination is not a talent of some men but is the health of every man",
"Most of the shadows of life are caused by standing in our own sunshine",
"Listen to your intuition. It will tell you everything you need to know",
"Know how to listen, and you will profit even from those who talk badly",
"Kindness is the language which the deaf can hear and the blind can see",
"Happiness often sneaks in through a door you didn't know you left open",
"The smallest act of kindness is worth more than the grandest intention",
"The noblest worship is to make yourself as good and as just as you can",
"If you do what you've always done, you'll get what youve always gotten",
"One who is too insistent on his own views, finds few to agree with him",
"If one way be better than another, that you may be sure is natures way",
"Letting go isn't the end of the world; it's the beginning of a new life",
"Our greatest glory is not in never failing but rising everytime we fall",
"If you think you can, you can. And if you think you can't, you're right",
"Slow down and everything you are chasing will come around and catch you",
"Your worst enemy cannot harm you as much as your own unguarded thoughts",
"You have to do your own growing no matter how tall your grandfather was",
"A man of ability and the desire to accomplish something can do anything",
"If you change the way you look at things, the things you look at change",
"Don't judge each day by the harvest you reap but by the seeds you plant",
"He who lives in harmony with himself lives in harmony with the universe",
"You might well remember that nothing can bring you success but yourself",
"Never tell me the sky's the limit when there are footprints on the moon",
"In the long run we get no more than we have been willing to risk giving",
"The best thing about the future is that it only comes one day at a time",
"Believe deep down in your heart that you're destined to do great things",
"Peace cannot be kept by force. It can only be achieved by understanding",
"Doing what you love is the cornerstone of having abundance in your life",
"The personal life deeply lived always expands into truths beyond itself",
"If you love life, don't waste time, for time is what life is made up of",
"Imagination is the living power and prime agent of all human perception",
"The exercise of an extraordinary gift is the supremest pleasure in life",
"I am not afraid of tomorrow, for I have seen yesterday and I love today",
"Truth, and goodness, and beauty are but different faces of the same all",
"Obstacles are those things you see when you take your eyes off the goal",
"I don't believe in failure. It's not failure if you enjoyed the process",
"Learn to listen. Opportunity could be knocking at your door very softly",
"He who wishes to secure the good of others, has already secured his own",
"It's not who you are that holds you back, it's who you think you're not"        
 ]
 return random.choice(sentences)
# create message
message=random_sentence()
# Create payload
payload = json.dumps({"text": message})
# Make the POST request
response = requests.post(url, headers=headers, data=payload)
# Print response
if response.status_code == 200:
 print("Message posted successfully.")
else:
 print(f"Failed to post message. Response code: {response.status_code}, Response body: {response.text}")
